// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class CarritoItem
{
    public int IdItem { get; set; }

    public int IdCarrito { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual Carrito IdCarritoNavigation { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }
}