// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Ciudad
{
    public int IdCiudad { get; set; }

    public string Nombre { get; set; }

    public int IdPais { get; set; }

    public virtual Pai IdPaisNavigation { get; set; }

    public virtual ICollection<Localidad> Localidads { get; set; } = new List<Localidad>();
}