// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class ClienteObraSocial
{
    public int IdClienteObraSocial { get; set; }

    public int IdCliente { get; set; }

    public int IdObraSocial { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ObrasSociale IdObraSocialNavigation { get; set; }
}