// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class DetalleReembolso
{
    public int IdDetalleReembolso { get; set; }

    public int IdReembolso { get; set; }

    public int NroFactura { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public decimal MontoRembolso { get; set; }

    public int IdCobertura { get; set; }

    public DateOnly FechaAplicacion { get; set; }

    public virtual Cobertura IdCoberturaNavigation { get; set; }

    public virtual Reembolso IdReembolsoNavigation { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}