// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class DetallesRecetum
{
    public int NroDetalleReceta { get; set; }

    public int NroReceta { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }

    public virtual Recetum NroRecetaNavigation { get; set; }
}