// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Entrega
{
    public int IdEntrega { get; set; }

    public int Fecha { get; set; }

    public int IdLogistica { get; set; }

    public int IdProveedor { get; set; }

    public int IdSucursal { get; set; }

    public int IdEmpleadoExterno { get; set; }

    public int IdEmpleadoReceptor { get; set; }

    public virtual ICollection<DetalleEntrega> DetalleEntregas { get; set; } = new List<DetalleEntrega>();

    public virtual EmpleadoExterno IdEmpleadoExternoNavigation { get; set; }

    public virtual EmpleadosInterno IdEmpleadoReceptorNavigation { get; set; }

    public virtual EmpresaLogistica IdLogisticaNavigation { get; set; }

    public virtual Proveedor IdProveedorNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }
}