// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class EstadoRespaldo
{
    public int IdEstadoRespaldo { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DetalleRespaldo> DetalleRespaldos { get; set; } = new List<DetalleRespaldo>();

    public virtual ICollection<Respaldo> Respaldos { get; set; } = new List<Respaldo>();
}