// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Reembolso
{
    public int IdReembolso { get; set; }

    public int IdObraSocial { get; set; }

    public int Fecha { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetalleReembolso> DetalleReembolsos { get; set; } = new List<DetalleReembolso>();

    public virtual ObrasSociale IdObraSocialNavigation { get; set; }
}