// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Respaldo
{
    public int IdRespaldo { get; set; }

    public int CodigoRespaldo { get; set; }

    public int NroReceta { get; set; }

    public int FechaRespaldo { get; set; }

    public int IdEstadoRespaldo { get; set; }

    public int? IdFactura { get; set; }

    public virtual ICollection<DetalleRespaldo> DetalleRespaldos { get; set; } = new List<DetalleRespaldo>();

    public virtual EstadoRespaldo IdEstadoRespaldoNavigation { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual Recetum NroRecetaNavigation { get; set; }
}