// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Sucursale
{
    public int IdSucursal { get; set; }

    public string Nombre { get; set; }

    public int Telefono { get; set; }

    public int IdDireccion { get; set; }

    public virtual ICollection<EmpleadosInterno> EmpleadosInternos { get; set; } = new List<EmpleadosInterno>();

    public virtual ICollection<Entrega> Entregas { get; set; } = new List<Entrega>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Direccion IdDireccionNavigation { get; set; }
}