// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FARMACIA.Models;

public partial class Suministro
{
    public int IdSuministro { get; set; }

    public int CodBarra { get; set; }

    public string Descripcion { get; set; }

    public double PrecioUnitario { get; set; }

    public int IdTipoSuministro { get; set; }

    public int IdTipoVenta { get; set; }

    public string UrlImagen { get; set; }

    public int Stock { get; set; }

    public virtual ICollection<CarritoItem> CarritoItems { get; set; } = new List<CarritoItem>();

    public virtual ICollection<DetalleEntrega> DetalleEntregas { get; set; } = new List<DetalleEntrega>();

    public virtual ICollection<DetalleReembolso> DetalleReembolsos { get; set; } = new List<DetalleReembolso>();

    public virtual ICollection<DetalleRespaldo> DetalleRespaldos { get; set; } = new List<DetalleRespaldo>();

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual ICollection<DetallesRecetum> DetallesReceta { get; set; } = new List<DetallesRecetum>();

    public virtual TiposSuministro IdTipoSuministroNavigation { get; set; }

    public virtual TiposVentum IdTipoVentaNavigation { get; set; }
}