// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FARMACIA.Models;

public partial class tpi_farmaciaContext : DbContext
{
    public tpi_farmaciaContext(DbContextOptions<tpi_farmaciaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Barrio> Barrios { get; set; }

    public virtual DbSet<Carrito> Carritos { get; set; }

    public virtual DbSet<CarritoItem> CarritoItems { get; set; }

    public virtual DbSet<Ciudad> Ciudads { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<ClienteObraSocial> ClienteObraSocials { get; set; }

    public virtual DbSet<Cobertura> Coberturas { get; set; }

    public virtual DbSet<Contacto> Contactos { get; set; }

    public virtual DbSet<DetalleEntrega> DetalleEntregas { get; set; }

    public virtual DbSet<DetalleReembolso> DetalleReembolsos { get; set; }

    public virtual DbSet<DetalleRespaldo> DetalleRespaldos { get; set; }

    public virtual DbSet<DetallesFactura> DetallesFacturas { get; set; }

    public virtual DbSet<DetallesRecetum> DetallesReceta { get; set; }

    public virtual DbSet<Direccion> Direccions { get; set; }

    public virtual DbSet<EmpleadoExterno> EmpleadoExternos { get; set; }

    public virtual DbSet<EmpleadosInterno> EmpleadosInternos { get; set; }

    public virtual DbSet<EmpresaLogistica> EmpresaLogisticas { get; set; }

    public virtual DbSet<Entrega> Entregas { get; set; }

    public virtual DbSet<EstadoRespaldo> EstadoRespaldos { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FormaPago> FormaPagos { get; set; }

    public virtual DbSet<Localidad> Localidads { get; set; }

    public virtual DbSet<Medico> Medicos { get; set; }

    public virtual DbSet<Mese> Meses { get; set; }

    public virtual DbSet<ObrasSociale> ObrasSociales { get; set; }

    public virtual DbSet<Pai> Pais { get; set; }

    public virtual DbSet<Proveedor> Proveedors { get; set; }

    public virtual DbSet<Recetum> Receta { get; set; }

    public virtual DbSet<Reembolso> Reembolsos { get; set; }

    public virtual DbSet<Respaldo> Respaldos { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Sucursale> Sucursales { get; set; }

    public virtual DbSet<Suministro> Suministros { get; set; }

    public virtual DbSet<TipoContacto> TipoContactos { get; set; }

    public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }

    public virtual DbSet<TiposSuministro> TiposSuministros { get; set; }

    public virtual DbSet<TiposVentum> TiposVenta { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barrio>(entity =>
        {
            entity.HasKey(e => e.IdBarrio).HasName("PK__Barrios__1121F0B208463750");

            entity.Property(e => e.IdBarrio)
                .ValueGeneratedNever()
                .HasColumnName("id_barrio");
            entity.Property(e => e.IdLocalidad).HasColumnName("id_localidad");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdLocalidadNavigation).WithMany(p => p.Barrios)
                .HasForeignKey(d => d.IdLocalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Barrios__id_loca__5165187F");
        });

        modelBuilder.Entity<Carrito>(entity =>
        {
            entity.HasKey(e => e.IdCarrito).HasName("PK__Carritos__83A2AD9CDBA920E5");

            entity.Property(e => e.IdCarrito).HasColumnName("id_carrito");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("activo")
                .HasColumnName("estado");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fecha_creacion");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Carritos)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carritos__estado__395884C4");
        });

        modelBuilder.Entity<CarritoItem>(entity =>
        {
            entity.HasKey(e => e.IdItem).HasName("PK__Carrito___87C9438BED38A550");

            entity.ToTable("Carrito_Items");

            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdCarrito).HasColumnName("id_carrito");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");
            entity.Property(e => e.PrecioUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_unitario");

            entity.HasOne(d => d.IdCarritoNavigation).WithMany(p => p.CarritoItems)
                .HasForeignKey(d => d.IdCarrito)
                .HasConstraintName("FK__Carrito_I__id_ca__3C34F16F");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.CarritoItems)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carrito_I__id_su__3D2915A8");
        });

        modelBuilder.Entity<Ciudad>(entity =>
        {
            entity.HasKey(e => e.IdCiudad).HasName("PK__Ciudad__B7DC4CD509E6406F");

            entity.ToTable("Ciudad");

            entity.Property(e => e.IdCiudad)
                .ValueGeneratedNever()
                .HasColumnName("id_ciudad");
            entity.Property(e => e.IdPais).HasColumnName("id_pais");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdPaisNavigation).WithMany(p => p.Ciudads)
                .HasForeignKey(d => d.IdPais)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ciudad__id_pais__4BAC3F29");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__Clientes__677F38F585D28B36");

            entity.Property(e => e.IdCliente)
                .ValueGeneratedNever()
                .HasColumnName("id_cliente");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Contrasena)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("contrasena");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.IdTipoUsuario).HasColumnName("id_tipo_usuario");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdDireccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Clientes__id_dir__60A75C0F");

            entity.HasOne(d => d.IdTipoUsuarioNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdTipoUsuario)
                .HasConstraintName("FK__Clientes__id_tip__40058253");
        });

        modelBuilder.Entity<ClienteObraSocial>(entity =>
        {
            entity.HasKey(e => e.IdClienteObraSocial).HasName("PK__Cliente___7CBE496AC31DC577");

            entity.ToTable("Cliente_Obra_Social");

            entity.Property(e => e.IdClienteObraSocial)
                .ValueGeneratedNever()
                .HasColumnName("id_cliente_obra_social");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdObraSocial).HasColumnName("id_obra_social");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.ClienteObraSocials)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cliente_O__id_cl__73BA3083");

            entity.HasOne(d => d.IdObraSocialNavigation).WithMany(p => p.ClienteObraSocials)
                .HasForeignKey(d => d.IdObraSocial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cliente_O__id_ob__74AE54BC");
        });

        modelBuilder.Entity<Cobertura>(entity =>
        {
            entity.HasKey(e => e.IdCobertura).HasName("PK__Cobertur__E64144A078C142FE");

            entity.Property(e => e.IdCobertura)
                .ValueGeneratedNever()
                .HasColumnName("id_cobertura");
            entity.Property(e => e.IdLocalidad).HasColumnName("id_localidad");
            entity.Property(e => e.IdMes).HasColumnName("id_mes");
            entity.Property(e => e.IdObraSocial).HasColumnName("id_obra_social");
            entity.Property(e => e.IdTipoSuministro).HasColumnName("id_tipo_suministro");
            entity.Property(e => e.PorcCobertura).HasColumnName("porc_cobertura");

            entity.HasOne(d => d.IdLocalidadNavigation).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.IdLocalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cobertura__id_lo__797309D9");

            entity.HasOne(d => d.IdMesNavigation).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.IdMes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cobertura__id_me__787EE5A0");

            entity.HasOne(d => d.IdObraSocialNavigation).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.IdObraSocial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cobertura__id_ob__7A672E12");

            entity.HasOne(d => d.IdTipoSuministroNavigation).WithMany(p => p.Coberturas)
                .HasForeignKey(d => d.IdTipoSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cobertura__id_ti__778AC167");
        });

        modelBuilder.Entity<Contacto>(entity =>
        {
            entity.HasKey(e => e.IdContacto).HasName("PK__Contacto__099A52B851171CEC");

            entity.Property(e => e.IdContacto)
                .ValueGeneratedNever()
                .HasColumnName("id_contacto");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");
            entity.Property(e => e.Valor)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("valor");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contactos__id_cl__656C112C");

            entity.HasOne(d => d.IdTipoContactoNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdTipoContacto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contactos__id_ti__66603565");
        });

        modelBuilder.Entity<DetalleEntrega>(entity =>
        {
            entity.HasKey(e => e.IdDetalle).HasName("PK__Detalle___4F1332DED343D120");

            entity.ToTable("Detalle_Entrega");

            entity.Property(e => e.IdDetalle)
                .ValueGeneratedNever()
                .HasColumnName("id_detalle");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdEntrega).HasColumnName("id_entrega");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");

            entity.HasOne(d => d.IdEntregaNavigation).WithMany(p => p.DetalleEntregas)
                .HasForeignKey(d => d.IdEntrega)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_E__id_en__32AB8735");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.DetalleEntregas)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_E__id_su__339FAB6E");
        });

        modelBuilder.Entity<DetalleReembolso>(entity =>
        {
            entity.HasKey(e => e.IdDetalleReembolso).HasName("PK__Detalle___1C649FD6BFF073D2");

            entity.ToTable("Detalle_Reembolso");

            entity.Property(e => e.IdDetalleReembolso)
                .ValueGeneratedNever()
                .HasColumnName("id_detalle_reembolso");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.FechaAplicacion).HasColumnName("fecha_aplicacion");
            entity.Property(e => e.IdCobertura).HasColumnName("id_cobertura");
            entity.Property(e => e.IdReembolso).HasColumnName("id_reembolso");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");
            entity.Property(e => e.MontoRembolso)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("monto_rembolso");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");

            entity.HasOne(d => d.IdCoberturaNavigation).WithMany(p => p.DetalleReembolsos)
                .HasForeignKey(d => d.IdCobertura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_co__1EA48E88");

            entity.HasOne(d => d.IdReembolsoNavigation).WithMany(p => p.DetalleReembolsos)
                .HasForeignKey(d => d.IdReembolso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_re__1BC821DD");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.DetalleReembolsos)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_su__1DB06A4F");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetalleReembolsos)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__nro_f__1CBC4616");
        });

        modelBuilder.Entity<DetalleRespaldo>(entity =>
        {
            entity.HasKey(e => e.IdDetalleRespaldo).HasName("PK__Detalle___469DB852C275566F");

            entity.ToTable("Detalle_Respaldo");

            entity.Property(e => e.IdDetalleRespaldo)
                .ValueGeneratedNever()
                .HasColumnName("id_detalle_respaldo");
            entity.Property(e => e.CantidadAprobada).HasColumnName("cantidad_aprobada");
            entity.Property(e => e.CantidadSolicitada).HasColumnName("cantidad_solicitada");
            entity.Property(e => e.IdEstadoRespaldo).HasColumnName("id_estado_respaldo");
            entity.Property(e => e.IdRespaldo).HasColumnName("id_respaldo");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");

            entity.HasOne(d => d.IdEstadoRespaldoNavigation).WithMany(p => p.DetalleRespaldos)
                .HasForeignKey(d => d.IdEstadoRespaldo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_es__160F4887");

            entity.HasOne(d => d.IdRespaldoNavigation).WithMany(p => p.DetalleRespaldos)
                .HasForeignKey(d => d.IdRespaldo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_re__14270015");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.DetalleRespaldos)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalle_R__id_su__151B244E");
        });

        modelBuilder.Entity<DetallesFactura>(entity =>
        {
            entity.HasKey(e => e.NroDetalleFactura).HasName("PK__Detalles__C9E29E6B64A590FE");

            entity.ToTable("Detalles_Factura");

            entity.Property(e => e.NroDetalleFactura)
                .ValueGeneratedNever()
                .HasColumnName("nro_detalle_factura");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");
            entity.Property(e => e.PreUnitario).HasColumnName("pre_unitario");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalles___id_su__02FC7413");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetallesFacturas)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalles___nro_f__02084FDA");
        });

        modelBuilder.Entity<DetallesRecetum>(entity =>
        {
            entity.HasKey(e => e.NroDetalleReceta).HasName("PK__Detalles__F45AC7EB5D61A6DF");

            entity.ToTable("Detalles_receta");

            entity.Property(e => e.NroDetalleReceta)
                .ValueGeneratedNever()
                .HasColumnName("nro_detalle_receta");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdSuministro).HasColumnName("id_suministro");
            entity.Property(e => e.NroReceta).HasColumnName("nro_receta");

            entity.HasOne(d => d.IdSuministroNavigation).WithMany(p => p.DetallesReceta)
                .HasForeignKey(d => d.IdSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalles___id_su__0A9D95DB");

            entity.HasOne(d => d.NroRecetaNavigation).WithMany(p => p.DetallesReceta)
                .HasForeignKey(d => d.NroReceta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Detalles___nro_r__09A971A2");
        });

        modelBuilder.Entity<Direccion>(entity =>
        {
            entity.HasKey(e => e.IdDireccion).HasName("PK__Direccio__25C35D07A44C2C89");

            entity.ToTable("Direccion");

            entity.Property(e => e.IdDireccion)
                .ValueGeneratedNever()
                .HasColumnName("id_direccion");
            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.NomCalle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nom_calle");
            entity.Property(e => e.NroCalle).HasColumnName("nro_calle");

            entity.HasOne(d => d.IdBarrioNavigation).WithMany(p => p.Direccions)
                .HasForeignKey(d => d.IdBarrio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Direccion__id_ba__5441852A");
        });

        modelBuilder.Entity<EmpleadoExterno>(entity =>
        {
            entity.HasKey(e => e.IdEmpleadoExterno).HasName("PK__Empleado__C43FE3BC91C3BED5");

            entity.ToTable("Empleado_Externo");

            entity.Property(e => e.IdEmpleadoExterno)
                .ValueGeneratedNever()
                .HasColumnName("id_empleado_externo");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<EmpleadosInterno>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK__Empleado__88B513945E797ED8");

            entity.ToTable("Empleados_internos");

            entity.Property(e => e.IdEmpleado)
                .ValueGeneratedNever()
                .HasColumnName("id_empleado");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.IdSucursal).HasColumnName("id_sucursal");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.EmpleadosInternos)
                .HasForeignKey(d => d.IdDireccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleados__id_di__282DF8C2");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.EmpleadosInternos)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleados__id_ro__29221CFB");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.EmpleadosInternos)
                .HasForeignKey(d => d.IdSucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Empleados__id_su__2739D489");
        });

        modelBuilder.Entity<EmpresaLogistica>(entity =>
        {
            entity.HasKey(e => e.IdLogistica).HasName("PK__Empresa___889ADDD922C5BFE1");

            entity.ToTable("Empresa_Logistica");

            entity.Property(e => e.IdLogistica)
                .ValueGeneratedNever()
                .HasColumnName("id_logistica");
            entity.Property(e => e.Cuit)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("cuit");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Entrega>(entity =>
        {
            entity.HasKey(e => e.IdEntrega).HasName("PK__Entregas__017C2C8A1941CC28");

            entity.Property(e => e.IdEntrega)
                .ValueGeneratedNever()
                .HasColumnName("id_entrega");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdEmpleadoExterno).HasColumnName("id_empleado_externo");
            entity.Property(e => e.IdEmpleadoReceptor).HasColumnName("id_empleado_receptor");
            entity.Property(e => e.IdLogistica).HasColumnName("id_logistica");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdSucursal).HasColumnName("id_sucursal");

            entity.HasOne(d => d.IdEmpleadoExternoNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.IdEmpleadoExterno)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__id_emp__2EDAF651");

            entity.HasOne(d => d.IdEmpleadoReceptorNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.IdEmpleadoReceptor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__id_emp__2FCF1A8A");

            entity.HasOne(d => d.IdLogisticaNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.IdLogistica)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__id_log__2BFE89A6");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.IdProveedor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__id_pro__2CF2ADDF");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Entregas)
                .HasForeignKey(d => d.IdSucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Entregas__id_suc__2DE6D218");
        });

        modelBuilder.Entity<EstadoRespaldo>(entity =>
        {
            entity.HasKey(e => e.IdEstadoRespaldo).HasName("PK__Estado_R__CD606870234F5167");

            entity.ToTable("Estado_Respaldo");

            entity.Property(e => e.IdEstadoRespaldo)
                .ValueGeneratedNever()
                .HasColumnName("id_estado_respaldo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.NroFactura).HasName("PK__Facturas__B31FA9AF858D8BF5");

            entity.Property(e => e.NroFactura)
                .ValueGeneratedNever()
                .HasColumnName("nro_factura");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.IdSucursal).HasColumnName("id_Sucursal");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__id_cli__7D439ABD");

            entity.HasOne(d => d.IdFormaPagoNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdFormaPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__id_for__7F2BE32F");

            entity.HasOne(d => d.IdSucursalNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdSucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__id_Suc__7E37BEF6");
        });

        modelBuilder.Entity<FormaPago>(entity =>
        {
            entity.HasKey(e => e.IdFormaPago).HasName("PK__Forma_Pa__DA9B39EE553FD2A1");

            entity.ToTable("Forma_Pago");

            entity.Property(e => e.IdFormaPago)
                .ValueGeneratedNever()
                .HasColumnName("id_forma_pago");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Localidad>(entity =>
        {
            entity.HasKey(e => e.IdLocalidad).HasName("PK__Localida__9A5E82AA0B078604");

            entity.ToTable("Localidad");

            entity.Property(e => e.IdLocalidad)
                .ValueGeneratedNever()
                .HasColumnName("id_localidad");
            entity.Property(e => e.IdCiudad).HasColumnName("id_ciudad");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdCiudadNavigation).WithMany(p => p.Localidads)
                .HasForeignKey(d => d.IdCiudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Localidad__id_ci__4E88ABD4");
        });

        modelBuilder.Entity<Medico>(entity =>
        {
            entity.HasKey(e => e.Matricula).HasName("PK__Medicos__30962D14AE39DA49");

            entity.Property(e => e.Matricula)
                .ValueGeneratedNever()
                .HasColumnName("matricula");
            entity.Property(e => e.Activo).HasColumnName("activo");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Mese>(entity =>
        {
            entity.HasKey(e => e.IdMes).HasName("PK__Meses__6C8AF5372B333503");

            entity.Property(e => e.IdMes)
                .ValueGeneratedNever()
                .HasColumnName("id_mes");
            entity.Property(e => e.Mes)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mes");
        });

        modelBuilder.Entity<ObrasSociale>(entity =>
        {
            entity.HasKey(e => e.IdObraSocial).HasName("PK__Obras_so__89039DF6BBE28242");

            entity.ToTable("Obras_sociales");

            entity.Property(e => e.IdObraSocial)
                .ValueGeneratedNever()
                .HasColumnName("id_obra_social");
            entity.Property(e => e.Cuit).HasColumnName("cuit");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono).HasColumnName("telefono");
        });

        modelBuilder.Entity<Pai>(entity =>
        {
            entity.HasKey(e => e.IdPais).HasName("PK__Pais__0941A3A76E8A9605");

            entity.Property(e => e.IdPais)
                .ValueGeneratedNever()
                .HasColumnName("id_pais");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Proveedor>(entity =>
        {
            entity.HasKey(e => e.IdProveedor).HasName("PK__Proveedo__8D3DFE28D6C74449");

            entity.ToTable("Proveedor");

            entity.Property(e => e.IdProveedor)
                .ValueGeneratedNever()
                .HasColumnName("id_proveedor");
            entity.Property(e => e.Cuit)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("cuit");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Recetum>(entity =>
        {
            entity.HasKey(e => e.NroReceta).HasName("PK__Receta__6658081646A2212E");

            entity.Property(e => e.NroReceta)
                .ValueGeneratedNever()
                .HasColumnName("nro_receta");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.Matricula).HasColumnName("matricula");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Receta)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Receta__id_clien__05D8E0BE");

            entity.HasOne(d => d.MatriculaNavigation).WithMany(p => p.Receta)
                .HasForeignKey(d => d.Matricula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Receta__matricul__06CD04F7");
        });

        modelBuilder.Entity<Reembolso>(entity =>
        {
            entity.HasKey(e => e.IdReembolso).HasName("PK__Reembols__51DA5136C94D6385");

            entity.Property(e => e.IdReembolso)
                .ValueGeneratedNever()
                .HasColumnName("id_reembolso");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estado");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.IdObraSocial).HasColumnName("id_obra_social");

            entity.HasOne(d => d.IdObraSocialNavigation).WithMany(p => p.Reembolsos)
                .HasForeignKey(d => d.IdObraSocial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Reembolso__id_ob__18EBB532");
        });

        modelBuilder.Entity<Respaldo>(entity =>
        {
            entity.HasKey(e => e.IdRespaldo).HasName("PK__Respaldo__41B4F7736278537B");

            entity.Property(e => e.IdRespaldo)
                .ValueGeneratedNever()
                .HasColumnName("id_respaldo");
            entity.Property(e => e.CodigoRespaldo).HasColumnName("codigo_respaldo");
            entity.Property(e => e.FechaRespaldo).HasColumnName("fecha_respaldo");
            entity.Property(e => e.IdEstadoRespaldo).HasColumnName("id_estado_respaldo");
            entity.Property(e => e.IdFactura).HasColumnName("id_factura");
            entity.Property(e => e.NroReceta).HasColumnName("nro_receta");

            entity.HasOne(d => d.IdEstadoRespaldoNavigation).WithMany(p => p.Respaldos)
                .HasForeignKey(d => d.IdEstadoRespaldo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Respaldos__id_es__10566F31");

            entity.HasOne(d => d.IdFacturaNavigation).WithMany(p => p.Respaldos)
                .HasForeignKey(d => d.IdFactura)
                .HasConstraintName("FK__Respaldos__id_fa__114A936A");

            entity.HasOne(d => d.NroRecetaNavigation).WithMany(p => p.Respaldos)
                .HasForeignKey(d => d.NroReceta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Respaldos__nro_r__0F624AF8");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("PK__Roles__6ABCB5E01EC06D15");

            entity.Property(e => e.IdRol)
                .ValueGeneratedNever()
                .HasColumnName("id_rol");
            entity.Property(e => e.DescripcionRol)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion_rol");
        });

        modelBuilder.Entity<Sucursale>(entity =>
        {
            entity.HasKey(e => e.IdSucursal).HasName("PK__Sucursal__8D4556B4B456907E");

            entity.Property(e => e.IdSucursal)
                .ValueGeneratedNever()
                .HasColumnName("id_Sucursal");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono).HasColumnName("telefono");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Sucursales)
                .HasForeignKey(d => d.IdDireccion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Sucursale__id_di__693CA210");
        });

        modelBuilder.Entity<Suministro>(entity =>
        {
            entity.HasKey(e => e.IdSuministro).HasName("PK__Suminist__ABFE9BD113F13DC7");

            entity.Property(e => e.IdSuministro)
                .ValueGeneratedNever()
                .HasColumnName("id_suministro");
            entity.Property(e => e.CodBarra).HasColumnName("cod_barra");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.IdTipoSuministro).HasColumnName("id_tipo_suministro");
            entity.Property(e => e.IdTipoVenta).HasColumnName("id_tipo_venta");
            entity.Property(e => e.PrecioUnitario).HasColumnName("precio_unitario");
            entity.Property(e => e.Stock).HasColumnName("stock");
            entity.Property(e => e.UrlImagen)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("url_imagen");

            entity.HasOne(d => d.IdTipoSuministroNavigation).WithMany(p => p.Suministros)
                .HasForeignKey(d => d.IdTipoSuministro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Suministr__id_ti__6E01572D");

            entity.HasOne(d => d.IdTipoVentaNavigation).WithMany(p => p.Suministros)
                .HasForeignKey(d => d.IdTipoVenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Suministr__id_ti__6EF57B66");
        });

        modelBuilder.Entity<TipoContacto>(entity =>
        {
            entity.HasKey(e => e.IdTipoContacto).HasName("PK__Tipo_con__CA854C0D74F212E0");

            entity.ToTable("Tipo_contacto");

            entity.Property(e => e.IdTipoContacto)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_contacto");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TipoUsuario>(entity =>
        {
            entity.HasKey(e => e.IdTipoUsuario).HasName("PK__Tipo_Usu__B17D78C8DFE9D941");

            entity.ToTable("Tipo_Usuario");

            entity.Property(e => e.IdTipoUsuario)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_usuario");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<TiposSuministro>(entity =>
        {
            entity.HasKey(e => e.IdTipoSuministro).HasName("PK__Tipos_Su__22748C158E4B6F2D");

            entity.ToTable("Tipos_Suministros");

            entity.Property(e => e.IdTipoSuministro)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_suministro");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TiposVentum>(entity =>
        {
            entity.HasKey(e => e.IdTipoVenta).HasName("PK__Tipos_Ve__2D950228F6833FAE");

            entity.ToTable("Tipos_Venta");

            entity.Property(e => e.IdTipoVenta)
                .ValueGeneratedNever()
                .HasColumnName("id_tipo_venta");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}