// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Barrio
{
    public int IdBarrio { get; set; }

    public string Nombre { get; set; }

    public int IdLocalidad { get; set; }

    public virtual ICollection<Direccion> Direccions { get; set; } = new List<Direccion>();

    public virtual Localidad IdLocalidadNavigation { get; set; }
}