// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Carrito
{
    public int IdCarrito { get; set; }

    public int IdCliente { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<CarritoItem> CarritoItems { get; set; } = new List<CarritoItem>();

    public virtual Cliente IdClienteNavigation { get; set; }
}