// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdDireccion { get; set; }

    public string Email { get; set; }

    public string Contrasena { get; set; }

    public int? IdTipoUsuario { get; set; }

    public virtual ICollection<Carrito> Carritos { get; set; } = new List<Carrito>();

    public virtual ICollection<ClienteObraSocial> ClienteObraSocials { get; set; } = new List<ClienteObraSocial>();

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Direccion IdDireccionNavigation { get; set; }

    public virtual TipoUsuario IdTipoUsuarioNavigation { get; set; }

    public virtual ICollection<Recetum> Receta { get; set; } = new List<Recetum>();
}