// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Cobertura
{
    public int IdCobertura { get; set; }

    public int IdTipoSuministro { get; set; }

    public int PorcCobertura { get; set; }

    public int IdMes { get; set; }

    public int IdLocalidad { get; set; }

    public int IdObraSocial { get; set; }

    public virtual ICollection<DetalleReembolso> DetalleReembolsos { get; set; } = new List<DetalleReembolso>();

    public virtual Localidad IdLocalidadNavigation { get; set; }

    public virtual Mese IdMesNavigation { get; set; }

    public virtual ObrasSociale IdObraSocialNavigation { get; set; }

    public virtual TiposSuministro IdTipoSuministroNavigation { get; set; }
}