// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class DetalleRespaldo
{
    public int IdDetalleRespaldo { get; set; }

    public int IdRespaldo { get; set; }

    public int IdSuministro { get; set; }

    public int CantidadSolicitada { get; set; }

    public int CantidadAprobada { get; set; }

    public int IdEstadoRespaldo { get; set; }

    public virtual EstadoRespaldo IdEstadoRespaldoNavigation { get; set; }

    public virtual Respaldo IdRespaldoNavigation { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }
}