// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class DetalleEntrega
{
    public int IdDetalle { get; set; }

    public int IdEntrega { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public virtual Entrega IdEntregaNavigation { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }
}