// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class DetallesFactura
{
    public int NroDetalleFactura { get; set; }

    public int NroFactura { get; set; }

    public int IdSuministro { get; set; }

    public int Cantidad { get; set; }

    public decimal? PreUnitario { get; set; }

    public virtual Suministro IdSuministroNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}