// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Direccion
{
    public int IdDireccion { get; set; }

    public string NomCalle { get; set; }

    public int NroCalle { get; set; }

    public int IdBarrio { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual ICollection<EmpleadosInterno> EmpleadosInternos { get; set; } = new List<EmpleadosInterno>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<Sucursale> Sucursales { get; set; } = new List<Sucursale>();
}