// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class EmpleadoExterno
{
    public int IdEmpleadoExterno { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int Dni { get; set; }

    public virtual ICollection<Entrega> Entregas { get; set; } = new List<Entrega>();
}