// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class EmpleadosInterno
{
    public int IdEmpleado { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int IdSucursal { get; set; }

    public int IdDireccion { get; set; }

    public int IdRol { get; set; }

    public virtual ICollection<Entrega> Entregas { get; set; } = new List<Entrega>();

    public virtual Direccion IdDireccionNavigation { get; set; }

    public virtual Role IdRolNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }
}