// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class EmpresaLogistica
{
    public int IdLogistica { get; set; }

    public string Nombre { get; set; }

    public string Cuit { get; set; }

    public virtual ICollection<Entrega> Entregas { get; set; } = new List<Entrega>();
}