// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateTime Fecha { get; set; }

    public int IdCliente { get; set; }

    public int IdSucursal { get; set; }

    public int IdFormaPago { get; set; }

    public virtual ICollection<DetalleReembolso> DetalleReembolsos { get; set; } = new List<DetalleReembolso>();

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormaPago IdFormaPagoNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }

    public virtual ICollection<Respaldo> Respaldos { get; set; } = new List<Respaldo>();
}