// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Localidad
{
    public int IdLocalidad { get; set; }

    public string Nombre { get; set; }

    public int IdCiudad { get; set; }

    public virtual ICollection<Barrio> Barrios { get; set; } = new List<Barrio>();

    public virtual ICollection<Cobertura> Coberturas { get; set; } = new List<Cobertura>();

    public virtual Ciudad IdCiudadNavigation { get; set; }
}