// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Medico
{
    public int Matricula { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Recetum> Receta { get; set; } = new List<Recetum>();
}