// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Mese
{
    public int IdMes { get; set; }

    public string Mes { get; set; }

    public virtual ICollection<Cobertura> Coberturas { get; set; } = new List<Cobertura>();
}