// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class ObrasSociale
{
    public int IdObraSocial { get; set; }

    public string Nombre { get; set; }

    public int Telefono { get; set; }

    public string Email { get; set; }

    public int Cuit { get; set; }

    public virtual ICollection<ClienteObraSocial> ClienteObraSocials { get; set; } = new List<ClienteObraSocial>();

    public virtual ICollection<Cobertura> Coberturas { get; set; } = new List<Cobertura>();

    public virtual ICollection<Reembolso> Reembolsos { get; set; } = new List<Reembolso>();
}