// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class Recetum
{
    public int NroReceta { get; set; }

    public int IdCliente { get; set; }

    public int Matricula { get; set; }

    public int Fecha { get; set; }

    public virtual ICollection<DetallesRecetum> DetallesReceta { get; set; } = new List<DetallesRecetum>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Medico MatriculaNavigation { get; set; }

    public virtual ICollection<Respaldo> Respaldos { get; set; } = new List<Respaldo>();
}