// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Farmacia.Models;

public partial class TiposVentum
{
    public int IdTipoVenta { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<Suministro> Suministros { get; set; } = new List<Suministro>();
}